---
title: "dp-analysis"
output: html_document
---
```{r}
#install.packages("wordcloud2")
#install.packages("lubridate")
#install.packages("jiebaR")
#install.packages("jiebaRD")
#install.packages("vcd")
#install.packages("ggpubr")
#install.packages("rowr")
#install.packages("Rsentiment")
library(rtweet)
library(twitteR)
library(syuzhet)
library(tm)
library(SnowballC)
library(tidytext)
library(ggmap)
library(dplyr)
library(ggplot2)
library(lubridate)
library(wordcloud2)
library(jiebaR)
library(jiebaRD)
library(vcd)
library(ggpubr)
library(rowr)
library(readr)
library(stringr)
library(DT)
```

```{r}
# import data to excel format
dp1_1 <- read.csv("dp1-1.csv")
dp1_2 <- read.csv("dp1-2.csv")
dp1_3 <- read.csv("dp1-3.csv")
dp1_4 <- read.csv("dp1-4.csv")
dp1_5 <- read.csv("dp1-5.csv")

dp2_1 <- read.csv("dp2-1.csv")
dp2_2 <- read.csv("dp2-2.csv")
dp2_3 <- read.csv("dp2-3.csv")
dp2_4 <- read.csv("dp2-4.csv")
dp2_5 <- read.csv("dp2-5.csv")

dp3_1 <- read.csv("dp3-1.csv")
dp3_2 <- read.csv("dp3-2.csv")
dp3_3 <- read.csv("dp3-3.csv")
dp3_4 <- read.csv("dp3-4.csv")
dp3_5 <- read.csv("dp3-5.csv")
dp3_6 <- read.csv("dp3-6.csv")
dp3_7 <- read.csv("dp3-7.csv")
dp3_8 <- read.csv("dp3-8.csv")
dp3_9 <- read.csv("dp3-9.csv")
dp3_10 <- read.csv("dp3-10.csv")
```

```{r}
# Conbine data set
dp1 <- rbind(dp1_1, dp1_2, dp1_3, dp1_4, dp1_5)
dp2 <- rbind(dp2_1, dp2_2, dp2_3, dp2_4, dp2_5)
dp3 <- rbind(dp3_1, dp3_2, dp3_3, dp3_4, dp3_5, dp3_6, dp3_7, dp3_8, dp3_9, dp3_10)
```

```{r}
# Delete duplicate data
dp1 <- dp1[!duplicated(dp1),]
dp2 <- dp2[!duplicated(dp2),] 
dp3 <- dp3[!duplicated(dp3),] #删掉所有列上都重复的
```

```{r}
# Random sample, 20000 for each group
dp1 <- dp1[sample(nrow(dp1), 20000), ]
dp2 <- dp2[sample(nrow(dp2), 20000), ]
dp3 <- dp3[sample(nrow(dp3), 20000), ]
```

```{r}
# Create wordclouds for each group
# Group 1
dp1_text <- as.character(dp1$text)
seg <- qseg[dp1_text] #使用qseg类型分词
seg <- seg[nchar(seg)>1] #去除字符长度小于1的词
seg
# Set stopwords
all_stops <- c("and","of","http","to","for","in","on","the","with","at","or","from")
seg <- removeWords(seg, all_stops)
seg <- table(seg)
seg_50 <- sort(seg, decreasing = TRUE)[1:50]
#获得词频数前50的词
seg_50
barplot(seg_50)
wordcloud2(seg,size = 2, minRotation = -pi/2, maxRotation = -pi/2) # Create wordcloud

# Group 2
dp2_text <- as.character(dp2$text)
seg <- qseg[dp2_text] #使用qseg类型分词
seg <- seg[nchar(seg)>1] #去除字符长度小于1的词
seg

seg <- table(seg)
seg_50 <- sort(seg, decreasing = TRUE)[1:50]
#获得词频数前50的词
seg_50
barplot(seg_50)
wordcloud2(seg,size = 2, minRotation = -pi/2, maxRotation = -pi/2) # Create wordcloud

# Group 3
dp3_text <- as.character(dp3$text)
seg <- qseg[dp3_text] #使用qseg类型分词
seg <- seg[nchar(seg)>1] #去除字符长度小于1的词
seg
# Set stopwords
all_stops <- c("and","of","http","to","for","in","on","the","with","at","or","from")
seg <- removeWords(seg, all_stops)
seg <- table(seg)
seg_50 <- sort(seg, decreasing = TRUE)[1:50]
#获得词频数前50的词
seg_50
barplot(seg_50)
wordcloud2(seg,size = 2, minRotation = -pi/2, maxRotation = -pi/2) # Create wordcloud

```

```{r}
# merge different group, add group as a variable
group_1 <- rep(1, times = nrow(dp1))
dp1$group <- group_1
group_2 <- rep(2, times = nrow(dp2))
dp2$group <- group_2
group_3 <- rep(3, times = nrow(dp3))
dp3$group <- group_3

dp_all <- bind_rows(dp1,dp2,dp3)
dp_all$group = factor (dp_all$group, levels = c(1,2,3), labels = c("group1", "group2", "group3"))
head(dp_all)
```

```{r}
# Descriptive statistics - 定量数据
summary(dp_all)
dp_agg <- dp_all %>%
  select(display_text_width, followers_count, friends_count, listed_count, statuses_count, favourites_count, group) 
dp_stats <- aggregate(dp_agg[,(1:6)], by = list(dp_agg$group), FUN = mean)
colnames(dp_stats)[1] <- "group"
dp_stats

summary(dp_all$display_text_width) 
summary(dp_all$followers_count) 
summary(dp_all$friends_count) 
summary(dp_all$listed_count) 
summary(dp_all$statuses_count) 
summary(dp_all$favourites_count)
print(sd(dp_all$display_text_width))
print(sd(dp_all$followers_count))
print(sd(dp_all$friends_count))
print(sd(dp_all$listed_count))
print(sd(dp_all$statuses_count))
print(sd(dp_all$favourites_count))

# 定量数据图
p1 <- ggplot(data = dp_stats, aes(y = followers_count, x = group, fill = group)) +
  geom_bar(stat="identity") +
  theme_minimal()
p2 <- ggplot(data = dp_stats, aes(y = friends_count, x = group, fill = group)) +
  geom_bar(stat="identity") +
  theme_minimal()
p3 <- ggplot(data = dp_stats, aes(y = statuses_count, x = group, fill = group)) +
  geom_bar(stat="identity") +
  theme_minimal()
p4 <- ggplot(data = dp_stats, aes(y = favourites_count, x = group, fill = group)) +
  geom_bar(stat="identity") +
  theme_minimal()
ggarrange(p1,p2,p3,p4, ncol=2,nrow=2,labels=c("A","B","C","D"))
  
# Descriptive statistics - 分类数据
dp_all %>%
  group_by(source) %>%
  summarise(total = n()) %>%
  filter(source == "Facebook"|source == "Instagram"|source == "Tweetbot for iOS"|source == "TweetDeck"|source == "twittbot.net"|source == "Twitter for Android"|source == "Twitter for iPad"|source == "Twitter for iPhone"|source == "Twitter Web App"|source == "Twitter Web Client") %>%
  ggplot() +
  geom_bar(mapping = aes(x = reorder(source, total), y = total), stat = 'identity', fill = 'skyblue2') +
  coord_flip()
```

```{r}
# Statistical Analysis - Comparison the Followers over three groups
# Prepare dataset
df_folw <- cbind.fill(dp_agg$group, dp_agg$followers_count)
colnames(df_folw) <- c("group", "folw_n")
# Shapiro-Wilk normality test for three groups
# Error in shapiro.test(folw_n[group == "group1"]) : sample size must be between 3 and 5000
#with(df_folw, shapiro.test(folw_n[group == "group1"])) 
#with(df_folw, shapiro.test(folw_n[group == "group2"])) 
#with(df_folw, shapiro.test(folw_n[group == "group3"])) 
# From the output, the two p-values are smaller than the significance level 0.05 implying that the distribution of the data are not significantly different from the normal distribution. In other words, we cannot assume the normality.
# Group 1 vs. Group 2
# Test whether the two populations have the same variances
df_folw_12 <- df_folw %>%
  filter(group == "group1" | group == "group2")
res.ftest <- var.test(folw_n ~ group, data = df_folw_12)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_folw_12 <- t.test(folw_n ~ group, data = df_folw_12, var.equal = FALSE)
res_folw_12
# Group 2 vs. Group 3
# Test whether the two populations have the same variances
df_folw_23 <- df_folw %>%
  filter(group == "group2" | group == "group3")
res.ftest <- var.test(folw_n ~ group, data = df_folw_23)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_folw_23 <- t.test(folw_n ~ group, data = df_folw_23, var.equal = FALSE)
res_folw_23
# Group 1 vs. Group 3
# Test whether the two populations have the same variances
df_folw_13 <- df_folw %>%
  filter(group == "group1" | group == "group3")
res.ftest <- var.test(folw_n ~ group, data = df_folw_13)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_folw_13 <- t.test(folw_n ~ group, data = df_folw_13, var.equal = FALSE)
res_folw_13
```

```{r}
# Statistical Analysis - Comparison the Friends over three groups
# Prepare dataset
df_frid <- cbind.fill(dp_agg$group, dp_agg$friends_count)
colnames(df_frid) <- c("group", "frid_n")

# Group 1 vs. Group 2
# Test whether the two populations have the same variances
df_frid_12 <- df_frid %>%
  filter(group == "group1" | group == "group2")
res.ftest <- var.test(frid_n ~ group, data = df_frid_12)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_frid_12 <- t.test(frid_n ~ group, data = df_frid_12, var.equal = FALSE)
res_frid_12
# Group 2 vs. Group 3
# Test whether the two populations have the same variances
df_frid_23 <- df_frid %>%
  filter(group == "group2" | group == "group3")
res.ftest <- var.test(frid_n ~ group, data = df_frid_23)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_frid_23 <- t.test(frid_n ~ group, data = df_frid_23, var.equal = FALSE)
res_frid_23
# Group 1 vs. Group 3
# Test whether the two populations have the same variances
df_frid_13 <- df_frid %>%
  filter(group == "group1" | group == "group3")
res.ftest <- var.test(frid_n ~ group, data = df_frid_13)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_frid_13 <- t.test(frid_n ~ group, data = df_frid_13, var.equal = FALSE)
res_frid_13
```

```{r}
# Statistical Analysis - Comparison the Statuses over three groups
# Prepare dataset
df_stat <- cbind.fill(dp_agg$group, dp_agg$statuses_count)
colnames(df_stat) <- c("group", "stat_n")

# Group 1 vs. Group 2
# Test whether the two populations have the same variances
df_stat_12 <- df_stat %>%
  filter(group == "group1" | group == "group2")
res.ftest <- var.test(stat_n ~ group, data = df_stat_12)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_stat_12 <- t.test(stat_n ~ group, data = df_stat_12, var.equal = FALSE)
res_stat_12
# Group 2 vs. Group 3
# Test whether the two populations have the same variances
df_stat_23 <- df_stat %>%
  filter(group == "group2" | group == "group3")
res.ftest <- var.test(stat_n ~ group, data = df_stat_23)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_stat_23 <- t.test(stat_n ~ group, data = df_stat_23, var.equal = FALSE)
res_stat_23
# Group 1 vs. Group 3
# Test whether the two populations have the same variances
df_stat_13 <- df_stat %>%
  filter(group == "group1" | group == "group3")
res.ftest <- var.test(stat_n ~ group, data = df_stat_13)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_stat_13 <- t.test(stat_n ~ group, data = df_stat_13, var.equal = FALSE)
res_stat_13
```

```{r}
# Statistical Analysis - Comparison the Favourites over three groups
# Prepare dataset
df_favr <- cbind.fill(dp_agg$group, dp_agg$favourites_count)
colnames(df_favr) <- c("group", "favr_n")

# Group 1 vs. Group 2
# Test whether the two populations have the same variances
df_favr_12 <- df_favr %>%
  filter(group == "group1" | group == "group2")
res.ftest <- var.test(favr_n ~ group, data = df_favr_12)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_favr_12 <- t.test(favr_n ~ group, data = df_favr_12, var.equal = FALSE)
res_favr_12
# Group 2 vs. Group 3
# Test whether the two populations have the same variances
df_favr_23 <- df_favr %>%
  filter(group == "group2" | group == "group3")
res.ftest <- var.test(favr_n ~ group, data = df_favr_23)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_favr_23 <- t.test(favr_n ~ group, data = df_favr_23, var.equal = FALSE)
res_favr_23
# Group 1 vs. Group 3
# Test whether the two populations have the same variances
df_favr_13 <- df_favr %>%
  filter(group == "group1" | group == "group3")
res.ftest <- var.test(favr_n ~ group, data = df_favr_13)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_favr_13 <- t.test(favr_n ~ group, data = df_favr_13, var.equal = FALSE)
res_favr_13
```
```{r}
# Set date format
dp_all$date <- as.Date(dp_all$created_at)

# Set time format
dp_all$time <- ymd_hms(dp_all$created_at)
```

```{r}
# Time analysis
# Extract date to cover the NA
dp_all$date <- as.Date(dp_all$time)
# Create new time variables: roundhour, hour, roundmin, minute
ymd(19970316); myd(03199716); dmy(16031997)
test_date <- ymd_hms("1997-03-16 12:01:30")
dp_all$roundhour <- round_date(dp_all$time, 'hour')
dp_all$roundmin <- round_date(dp_all$time, "minute")
dp_all$hour <- hour(dp_all$roundhour)
dp_all$minute <- minute(dp_all$roundmin)
# Graph twitter counts in 24 hours
dp_all %>%
  group_by(group, hour) %>%
  summarise(total = n()) %>%
  filter(group == "group1" | group == "group3") %>%
  ggplot() +
  geom_bar(mapping = aes(x = hour, y = total, fill = group), stat = "identity")+
  geom_line(mapping = aes(x = hour, y = total, fill = group), colour = "navy") +
  theme_classic() 
# Focus on group 3
dp_all %>%
  group_by(group, hour) %>%
  summarise(total = n()) %>%
  filter(group == "group3") %>%
  ggplot() +
  geom_bar(mapping = aes(x = hour, y = total), stat = "identity", fill = "lightblue") +
  geom_line(mapping = aes(x = hour, y = total), colour = "navy") +
  theme_classic()
```

```{r}
# Sentiment analysis

# Extract text
dp_all$twttext <- as.character(dp_all$text)

# Text cleaning
dp_all$twttext %<>%
  gsub("(RT|via)((?:\\b\\w*@\\w+)+)", " ", .) %>%
  gsub("http[^[:blank:]]+", " ", .) %>%
  gsub("@\\w+", " ", .) %>%
  gsub("[[:punct:]]", " ", .) %>%
  gsub("[^[:alnum:]]", " ", .)
 
# All the groups
sentiment <- get_nrc_sentiment(dp_all$twttext, language = 'english')
stm.positive <- sum(sentiment$positive)
stm.anger <- sum(sentiment$anger)
stm.anticipation <- sum(sentiment$anticipation)
stm.disgust <- sum(sentiment$disgust)
stm.fear <- sum(sentiment$fear)
stm.joy <- sum(sentiment$joy)
stm.sadness <- sum(sentiment$sadness)
stm.surprise <- sum(sentiment$surprise)
stm.trust <- sum(sentiment$trust)
stm.negative <- sum(sentiment$negative)
```

# Group by groups

```{r}
# Group 1 sentiment score bar
dp_all_1 <- filter(dp_all, group == "group1") 
sentiment_1 <- get_nrc_sentiment(dp_all_1$twttext, language = 'english') 
stm.positive_1 <- sum(sentiment_1$positive) 
stm.anger_1 <- sum(sentiment_1$anger) 
stm.anticipation_1 <- sum(sentiment_1$anticipation) 
stm.disgust_1 <- sum(sentiment_1$disgust) 
stm.fear_1 <- sum(sentiment_1$fear) 
stm.joy_1 <- sum(sentiment_1$joy) 
stm.sadness_1 <- sum(sentiment_1$sadness) 
stm.surprise_1 <- sum(sentiment_1$surprise) 
stm.trust_1 <- sum(sentiment_1$trust) 
stm.negative_1 <- sum(sentiment_1$negative) 

sentiment_type_1 <- c("Positive", "Anger", "Anticipation", "Disgust", "Fear", "Joy", "Sadness", "Surprise", "Trust", "Negative") 
score_1 <- c(stm.positive_1, stm.anger_1, stm.anticipation_1, stm.disgust_1, stm.fear_1, stm.joy_1, stm.sadness_1, stm.surprise_1, stm.trust_1, stm.negative_1) 
sentiment_data_1 <- data.frame(sentiment_type_1, score_1)

yaxis_1 <- c(stm.positive_1, stm.anger_1, stm.anticipation_1, stm.disgust_1, stm.fear_1, stm.joy_1, stm.sadness_1, stm.surprise_1, stm.trust_1, stm.negative_1)
xaxis <- c("Positive", "Anger", "Anticipation", "Disgust", "Fear", "Joy", "Sadness", "Surprise", "Trust", "Negative")
color <- c("palegreen4", "orangered4", "palegreen3", "orangered3", "orangered4", "palegreen4", "orangered3", "palegreen3", "palegreen4", "orangered4")
yrange_1 <- range(0, 50000)
barplot(yaxis_1, names.arg = xaxis, xlab = "Sentiment Categories", ylab = "Sentiment Score of Group 1", main = "Group 1: Twitter sentiment for 'Depresson'", col = color, border = "white", ylim = yrange_1, cex.axis = 0.6, cex.names = 0.6)
stm_table_1 <- c(stm.positive_1, stm.anger_1, stm.anticipation_1, stm.disgust_1, stm.fear_1, stm.joy_1, stm.sadness_1, stm.surprise_1, stm.trust_1, stm.negative_1)
```

```{r}
# Group 2 sentiment score bar
dp_all_2 <- filter(dp_all, group == "group2") 
sentiment_2 <- get_nrc_sentiment(dp_all_2$twttext, language = 'english') 
stm.positive_2 <- sum(sentiment_2$positive) 
stm.anger_2 <- sum(sentiment_2$anger) 
stm.anticipation_2 <- sum(sentiment_2$anticipation) 
stm.disgust_2 <- sum(sentiment_2$disgust) 
stm.fear_2 <- sum(sentiment_2$fear) 
stm.joy_2 <- sum(sentiment_2$joy) 
stm.sadness_2 <- sum(sentiment_2$sadness) 
stm.surprise_2 <- sum(sentiment_2$surprise) 
stm.trust_2 <- sum(sentiment_2$trust) 
stm.negative_2 <- sum(sentiment_2$negative) 
# 创建sentiment数据框
sentiment_type_2 <- c("Positive", "Anger", "Anticipation", "Disgust", "Fear", "Joy", "Sadness", "Surprise", "Trust", "Negative") 
score_2 <- c(stm.positive_2, stm.anger_2, stm.anticipation_2, stm.disgust_2, stm.fear_2, stm.joy_2, stm.sadness_2, stm.surprise_2, stm.trust_2, stm.negative_2) 
sentiment_data_2 <- data.frame(sentiment_type_2, score_2)

yaxis_2 <- c(stm.positive_2, stm.anger_2, stm.anticipation_2, stm.disgust_2, stm.fear_2, stm.joy_2, stm.sadness_2, stm.surprise_2, stm.trust_2, stm.negative_2)
xaxis <- c("Positive", "Anger", "Anticipation", "Disgust", "Fear", "Joy", "Sadness", "Surprise", "Trust", "Negative")
color <- c("palegreen4", "orangered4", "palegreen3", "orangered3", "orangered4", "palegreen4", "orangered3", "palegreen3", "palegreen4", "orangered4")
yrange_2 <- range(0, yaxis_2)
barplot(yaxis_2, names.arg = xaxis, xlab = "Sentiment Categories", ylab = "Sentiment Score of Group 2", main = "Group 2: Twitter sentiment for 'Depresson'", col = color, border = "white", ylim = yrange_2, cex.axis = 0.6, cex.names = 0.6)
stm_table_2 <- c(stm.positive_2, stm.anger_2, stm.anticipation_2, stm.disgust_2, stm.fear_2, stm.joy_2, stm.sadness_2, stm.surprise_2, stm.trust_2, stm.negative_2)
```

```{r}
# Group 3 sentiment score bar
dp_all_3 <- filter(dp_all, group == "group3") 
sentiment_3 <- get_nrc_sentiment(dp_all_3$twttext, language = 'english') 
stm.positive_3 <- sum(sentiment_3$positive) 
stm.anger_3 <- sum(sentiment_3$anger) 
stm.anticipation_3 <- sum(sentiment_3$anticipation) 
stm.disgust_3 <- sum(sentiment_3$disgust) 
stm.fear_3 <- sum(sentiment_3$fear) 
stm.joy_3 <- sum(sentiment_3$joy) 
stm.sadness_3 <- sum(sentiment_3$sadness) 
stm.surprise_3 <- sum(sentiment_3$surprise) 
stm.trust_3 <- sum(sentiment_3$trust) 
stm.negative_3 <- sum(sentiment_3$negative) 
# 创建sentiment数据框
sentiment_type_3 <- c("Positive", "Anger", "Anticipation", "Disgust", "Fear", "Joy", "Sadness", "Surprise", "Trust", "Negative") 
score_3 <- c(stm.positive_3, stm.anger_3, stm.anticipation_3, stm.disgust_3, stm.fear_3, stm.joy_3, stm.sadness_3, stm.surprise_3, stm.trust_3, stm.negative_3) 
sentiment_data_3 <- data.frame(sentiment_type_3, score_3)

yaxis_3 <- c(stm.positive_3, stm.anger_3, stm.anticipation_3, stm.disgust_3, stm.fear_3, stm.joy_3, stm.sadness_3, stm.surprise_3, stm.trust_3, stm.negative_3)
xaxis <- c("Positive", "Anger", "Anticipation", "Disgust", "Fear", "Joy", "Sadness", "Surprise", "Trust", "Negative")
color <- c("palegreen4", "orangered4", "palegreen3", "orangered3", "orangered4", "palegreen4", "orangered3", "palegreen3", "palegreen4", "orangered4")
yrange_3 <- range(0, 50000)
barplot(yaxis_3, names.arg = xaxis, xlab = "Sentiment Categories", ylab = "Sentiment Score of Group 3", main = "Group 3: Twitter sentiment for 'Depresson'", col = color, border = "white", ylim = yrange_3, cex.axis = 0.6, cex.names = 0.6)
stm_table_3 <- c(stm.positive_3, stm.anger_3, stm.anticipation_3, stm.disgust_3, stm.fear_3, stm.joy_3, stm.sadness_3, stm.surprise_3, stm.trust_3, stm.negative_3)
```

```{r}
# linear regression

# Merge the columns of sentiment score into data
sentiment_test <- get_nrc_sentiment(dp_all$twttext, language = 'english')
sentiment_tt <- cbind(dp_all, sentiment_test)

# Convert the negative sentiment score to negative integers, add up to get a total sentiment score
sentiment_tt$sentiment_score <- sentiment_tt$positive + sentiment_tt$negative*(-1)
```

```{r}
# model_all
fit_all <- lm(sentiment_score ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt)
summary(fit_all)

# model_negative_all
fit_negative_all <- lm(negative ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt)
summary(fit_negative_all)

# model_positive_all
fit_positive_all <- lm(negative ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt)
summary(fit_positive_all)

# model_group1_all
sentiment_tt_1 <- filter(sentiment_tt, group == "group1")
fit_group1 <- lm(sentiment_score ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_1)
summary(fit_group1)

# model_group1_negative
sentiment_tt_1 <- filter(sentiment_tt, group == "group1")
fit_group1_negative <- lm(negative ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_1)
summary(fit_group1_negative)

# model_group1_positive
sentiment_tt_1 <- filter(sentiment_tt, group == "group1")
fit_group1_positive <- lm(positive ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_1)
summary(fit_group1_positive)

# model_group2_all
sentiment_tt_2 <- filter(sentiment_tt, group == "group2")
fit_group2 <- lm(sentiment_score ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_2)
summary(fit_group2)

# model_group2_negative
sentiment_tt_2 <- filter(sentiment_tt, group == "group2")
fit_group2_negative <- lm(negative ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_2)
summary(fit_group2_negative)

# model_group2_positive
sentiment_tt_2 <- filter(sentiment_tt, group == "group2")
fit_group2_positive <- lm(positive ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_2)
summary(fit_group2_positive)

# model_group3_all
sentiment_tt_3 <- filter(sentiment_tt, group == "group3")
fit_group3 <- lm(sentiment_score ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_3)
summary(fit_group3)

# model_group3_negative
sentiment_tt_3 <- filter(sentiment_tt, group == "group3")
fit_group3_negative <- lm(negative ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_3)
summary(fit_group3_negative)

# model_group3_positive
sentiment_tt_3 <- filter(sentiment_tt, group == "group3")
fit_group3_positive <- lm(positive ~ followers_count + friends_count + listed_count + statuses_count + favourites_count, data = sentiment_tt_3)
summary(fit_group3_positive)
```
```{r}
# Statistical Analysis - Comparison the Favourites over three groups
# Sentiment Score
# Prepare dataset
df_sentiment <- sentiment_tt %>%
  select(group, sentiment_score)

# Group 1 vs. Group 2
# Test whether the two populations have the same variances
df_sentiment_12 <- df_sentiment %>%
  filter(group == "group1" | group == "group2")
res.ftest <- var.test(sentiment_score ~ group, data = df_sentiment_12)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_sentiment_12 <- t.test(sentiment_score ~ group, data = df_sentiment_12, var.equal = TRUE)
res_sentiment_12
# Group 2 vs. Group 3
# Test whether the two populations have the same variances
df_sentiment_23 <- df_sentiment %>%
  filter(group == "group2" | group == "group3")
res.ftest <- var.test(sentiment_score ~ group, data = df_sentiment_23)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_sentiment_23 <- t.test(sentiment_score ~ group, data = df_sentiment_23, var.equal = TRUE)
res_sentiment_23
# Group 1 vs. Group 3
# Test whether the two populations have the same variances
df_sentiment_13 <- df_sentiment %>%
  filter(group == "group1" | group == "group3")
res.ftest <- var.test(sentiment_score ~ group, data = df_sentiment_13)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_sentiment_13 <- t.test(sentiment_score ~ group, data = df_sentiment_13, var.equal = TRUE)
res_sentiment_13
```

```{r}
# Statistical Analysis - Comparison the Favourites over three groups
# Positive
# Prepare dataset
df_postv <- sentiment_tt %>%
  select(group, positive)

# Group 1 vs. Group 2
# Test whether the two populations have the same variances
df_postv_12 <- df_postv %>%
  filter(group == "group1" | group == "group2")
res.ftest <- var.test(positive ~ group, data = df_postv_12)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_postv_12 <- t.test(positive ~ group, data = df_postv_12, var.equal = TRUE)
res_postv_12
# Group 2 vs. Group 3
# Test whether the two populations have the same variances
df_postv_23 <- df_postv %>%
  filter(group == "group2" | group == "group3")
res.ftest <- var.test(positive ~ group, data = df_postv_23)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_postv_23 <- t.test(positive ~ group, data = df_postv_23, var.equal = TRUE)
res_postv_23
# Group 1 vs. Group 3
# Test whether the two populations have the same variances
df_postv_13 <- df_postv %>%
  filter(group == "group1" | group == "group3")
res.ftest <- var.test(positive ~ group, data = df_postv_13)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_postv_13 <- t.test(positive ~ group, data = df_postv_13, var.equal = TRUE)
res_postv_13
```

```{r}
# Statistical Analysis - Comparison the Favourites over three groups
# Negative
# Prepare dataset
df_nega <- sentiment_tt %>%
  select(group, negative)

# Group 1 vs. Group 2
# Test whether the two populations have the same variances
df_nega_12 <- df_nega %>%
  filter(group == "group1" | group == "group2")
res.ftest <- var.test(negative ~ group, data = df_nega_12)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_nega_12 <- t.test(negative ~ group, data = df_nega_12, var.equal = TRUE)
res_nega_12

# Group 2 vs. Group 3
# Test whether the two populations have the same variances
df_nega_23 <- df_nega %>%
  filter(group == "group2" | group == "group3")
res.ftest <- var.test(negative ~ group, data = df_nega_23)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_nega_23 <- t.test(negative ~ group, data = df_nega_23, var.equal = TRUE)
res_nega_23
# Group 1 vs. Group 3
# Test whether the two populations have the same variances
df_nega_13 <- df_nega %>%
  filter(group == "group1" | group == "group3")
res.ftest <- var.test(negative ~ group, data = df_nega_13)
res.ftest
#The p-value of F-test is p < 0.05. It’s smaller than the significance level alpha = 0.05. In conclusion, there is a significant difference between the variances of the two sets of data.
#t-test
res_nega_13 <- t.test(negative ~ group, data = df_nega_13, var.equal = TRUE)
res_nega_13
```
